// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwakvuvlldnvbnxgvhaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3YWt2dXZsbGRudmJueGd2aGFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODg3NzMsImV4cCI6MjA2NjI2NDc3M30.mXD-g5IydABpKeWA2GSxdc90aR1hyn_ceUfUviBJq04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);